server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
spring.jpa.database: POSTGRESQL
spring.datasource.platform: postgres
spring.datasource.url: 
spring.datasource.username: 
spring.datasource.password: 
spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true