server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
spring.jpa.database: POSTGRESQL
spring.datasource.platform: postgres
spring.datasource.url: jdbc:postgresql://ec2-54-247-103-43.eu-west-1.compute.amazonaws.com:5432/de2d6b7k8534rs
spring.datasource.username: jkoakcyryfueqv
spring.datasource.password: cad6d7b2f69b5b785b59c685b6fe068d05960bfb68d35d2cf9a6fa7efe0bb97b
#spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring:
  session:
    jdbc:
      initialize-schema: embedded      
spring.session.store-type: jdbc

jwt.secret: go-gas-service